### ISSUE TITLE
Not working with Ipad

### ISSUE THREAD

**Issue by xbadal** [bytepark/auto_orientation#15]
this plugin does nothing in iPad. i have tested it and got no result.

**Comment by fbatschi** [comment]
@xbadal do you have more information? what kind of ipad? which iOS?
does it work in the simulator  or on real hardward for you?

**Comment by PieterAelse** [comment]
@xbadal any updates on the info? Or did you find any other way to get it working?

**Comment by Colton127** [comment]
You cannot control orientation on iPad unless if you specify the app as fullscreen in the info.plist.

info.plist
```
<key>UIRequiresFullScreen</key>
<true/>
```

Please see the example in my pull request: https://github.com/bytepark/auto_orientation/pull/26
