### ISSUE TITLE
[ios] MissingPluginException

### ISSUE THREAD

**Issue by os20** [bytepark/auto_orientation#2]
When I use this in Plugin on iOS I got this error:
<img width="1011" alt="Bildschirmfoto 2019-06-12 um 15 05 51" src="https://user-images.githubusercontent.com/1292531/59354748-fd085980-8d25-11e9-96d4-494e50a59c52.png">

What mean the error?

On Android is already fine

**Comment by sfaujour** [comment]
Hey @os20 
this error means that the method is not implemented in the ios part.

The iOS part does implement the "setLandscapeRight" method, for now, i don't know why this error happens.

i'll check out the latest version in an example app and give it a try.

**Comment by os20** [comment]
Thank you very much for the quick answer.
I look forward to a short feedback after you have tested it.

**Comment by sfaujour** [comment]
I've forgot to ask: Which version do you use? 1.0.1?

**Comment by os20** [comment]
Yes, I am using version 1.0.1.
<img width="220" alt="Bildschirmfoto 2019-06-12 um 16 40 53" src="https://user-images.githubusercontent.com/1292531/59360719-e9162500-8d30-11e9-83bb-50ef8d83e441.png">

**Comment by sfaujour** [comment]
Thats strange - i've checked out the example app and tried the `Landscape Mode` and everything works fine. Could try to run the example too?

I really don't know - maybe reinstalling the package, or doing a `flutter packages upgrade`

**Comment by os20** [comment]
That's really very strange.
In your example it works perfectly.

If I include it in my project, I always get the error message.

**Comment by sfaujour** [comment]
Can you try to run `flutter clean` and afterwards run the app again?

**Comment by os20** [comment]
Hi,

I've tried it. Still with the same result and the same error message.
