### ISSUE TITLE
Migrate to Android v2 Embedding API

### ISSUE THREAD

**Issue by rayliverified** [bytepark/auto_orientation#22]
Would be wonderful for this plugin to be migrated to the V2 embedding.

> The plugin `auto_orientation` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
> The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.

**Comment by thenexus00** [comment]
Is this going to be implemented Or does someone need to do an updated version of this? Is this plugin still being worked on?
Thanks.

**Comment by fbatschi** [comment]
If somebody would be willing to provide some Pull Requests, we can merge them.

**Comment by kingiol** [comment]
PR: https://github.com/bytepark/auto_orientation/pull/24

**Comment by fbatschi** [comment]
The PR of kingiol has been merged. Thank you for that. We will release a 2.1.0 soon.
