### ISSUE TITLE
tag 1.0.5 run error on ios

### ISSUE THREAD

**Issue by chavesgu** [bytepark/auto_orientation#5]
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010aa206fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000109d14ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010aa20555 +[NSException raise:format:] + 197
	3   UIKitCore                           0x0000000115e48647 -[UIViewController __supportedInterfaceOrientations] + 921
	4   UIKitCore                           0x0000000115e37ee5 -[UIViewController _preferredInterfaceOrientationGivenStatusBarAndDeviceAndOrientation:] + 90
	5   UIKitCore                           0x000000011646c851 -[UIWindow _updateToInterfaceOrientation:duration:force:] + 407
	6   CoreFoundation                      0x000000010a9625ec __CFNOTIFICATIONCENTER_IS_<…>

**Comment by sfaujour** [comment]
Is this still an issue?
