### ISSUE TITLE
Does not work on iOS

### ISSUE THREAD

**Issue by besserwisser** [bytepark/auto_orientation#6]
I tested it on an iPad (iOS 12.3.1) and it had no effect. Not in my app and not with the example app. 

Screen rotation is allowed in iOS.

Here a screen recording of the example app: [https://streamable.com/vve0p](https://streamable.com/vve0p)

**Comment by sfaujour** [comment]
Hey @besserwisser 
thats no a problem with iOS, it's a problem with iPad's in general, which is an offical flutter issue.

**Comment by sfaujour** [comment]
https://github.com/flutter/flutter/issues/27235

**Comment by anilslabs** [comment]
App crashing on iPhone 6

**Comment by SinoMiles** [comment]
@besserwisser  @sfaujour  did you fix the problem? I'm using iPad too.

**Comment by besserwisser** [comment]
> @besserwisser @sfaujour did you fix the problem? I'm using iPad too.

Nope, I did not fix it. You have to manually rotate the iPad.

**Comment by lishuu** [comment]
Same problem i encountered.
- iPhoneX
- iOS 13.3.1

**Comment by SinoMiles** [comment]
@besserwisser  @sfaujour 
 I has fix this problem.just select full screen,that can lock screen.
my ipad version is 12.0 .ipad simulator is 13.3

setPreferredOrientations method
Future<void> setPreferredOrientations (
List<DeviceOrientation> orientations
)
Specifies the set of orientations the application interface can be displayed in.

The orientation argument is a list of DeviceOrientation enum values. The empty list causes the application to defer to the operating system default.

Limitations
This setting will only be respected on iPad if multitasking is disabled.

You can decide to opt out of multitasking on iPad, then setPreferredOrientations will work but your app will not support Slide Over and Split View multitasking anymore.

Should you decide to opt out of multitasking you can do this by setting "Requires full screen" to true in the Xcode Deployment Info.
code here
```
void main() async {
  AutoOrientation.landscapeLeftMode();
  runApp( MyApp());
}
```
![image](https://user-images.githubusercontent.com/9588025/77131758-c4a56100-6a97-11ea-966c-b2b29ed578a6.png)
