### ISSUE TITLE
migrate to Android-X

### ISSUE THREAD

**Issue by kmusham** [bytepark/auto_orientation#7]
Hi,
Can you please migrate the libraries to android-x and also update the gradle version.
thanks

**Comment by shaxxx** [comment]
Second that.
Google Play is now forcing developer to use new Google Play API 3.
This should be trivial using Android Studio.
More info:
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by sfaujour** [comment]
Hey guy's thanks for reporting the issue. I will have a look at this! Thanks!
